#!/bin/bash

# Configure JWT Token TTL (Time To Live)
# This function creates a local configuration file that overrides the default JWT token TTL setting.
#
# What this script does:
# 1. Sets the JWT token TTL value from the JWT_TTL environment variable (defaults to 3600 seconds = 1 hour)
# 2. Creates a local YAML configuration file at config/packages/lexik_jwt_authentication_local.yaml
# 3. This local config file overrides the default lexik_jwt_authentication.yaml settings
# 4. The token_ttl parameter determines how long JWT tokens remain valid before expiring
#
# Environment variables:
# - JWT_TTL: Optional. The TTL value in seconds for JWT tokens. Default: 3600 (1 hour)
#
# Generated file:
# - config/packages/lexik_jwt_authentication_local.yaml: Auto-generated YAML config file
#
function configure_jwt_ttl() {
  echo "Configuring JWT token TTL..."
  TTL_VALUE="${JWT_TTL:-3600}"
  
  LOCAL_CONFIG="config/packages/lexik_jwt_authentication_local.yaml"
  
  cat > "$LOCAL_CONFIG" <<-EOF
	# Auto-generated by install script, overrides lexik_jwt_authentication.yaml
	lexik_jwt_authentication:
	    token_ttl: ${TTL_VALUE}
	EOF
  
  echo "Created ${LOCAL_CONFIG} with token_ttl: ${TTL_VALUE}s"
}
